### ISSUE TITLE
Add a "DO NOT EDIT" comment to failpoint-enabled source code

### ISSUE THREAD

**Issue by kennytm** [pingcap/failpoint#37]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Although `failpoint-ctl disable` will automatically apply diff when the original source is changed, this doesn't always work, and it would be frustrating to be stuck in a state where `failpoint-ctl disable` cannot proceed and you've got some changes hard to be extracted.

Most editors supporting Go recognize the [generated source indicator](https://golang.org/cmd/go/#hdr-Generate_Go_files_by_processing_source) and warns when you try to edit the file, thus preventing the need to merge diffs in the first place.

**Describe the feature you'd like:**

In the source code generated by `failpoint-ctl enable` (all of the rewritten `*.go`, `*__failpoint_binding__.go`, and `*.go__failpoint_stash__`), insert this comment on first line:

```go
// Code generated by failpoint DO NOT EDIT.
```

Remove this line after `failpoint-ctl disable`.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by lonng** [comment]
Can you file a PR for this feature? @kennytm

**Comment by kennytm** [comment]
Yeah when I've got time to do it 🙃
