### ISSUE TITLE
Create Release Binary amd and Darwin 

### ISSUE THREAD

**Issue by rahul8590** [pingcap/failpoint#57]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Yes

**Describe the feature you'd like:**

Release tags and binary for failpoint.

**Describe alternatives you've considered:**

Create git tags and release binary for both linux and mac builds?  Its easier for download the builds directly from github and include in CI/CD pipelines as apposed to clone the entire repo and make builds.

**Teachability, Documentation, Adoption, Optimization:**

Users wanting to include failopint in their build pipelines , could directly curl/wget the tar files from github and use `failpoint-ctl enable` in their repository. Its much simpler that way , instead of cloning the entire repo and making builds manually.

**Comment by bjwang112006** [comment]
go build -o failpoint-ctl.exe failpoint-ctl/main.go
