### ISSUE TITLE
How to inject faults to a program at running time with failpoint

### ISSUE THREAD

**Issue by yuxiaoba** [pingcap/failpoint#69]
## Question

The REDAME file teaches me how to use failpoint when staring a program. 

However, it does not tell about injecting faults to a program at running time.

For example,

First I start a go program : 
```
./test
```

After 5 mins,  I set the ENV `GO_FAILPOINTS="main/testPanic=return(true)"`

The fault cannot be injected to the program.

How can I inject faults to a program after running the progarm?

**Comment by soorajchirag** [comment]
@yuxiaoba: Did you figure this out?

**Comment by yuxiaoba** [comment]
> @yuxiaoba: Did you figure this out?
I find that I can invoke faults by http rather than environment variable.
